# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r


# Use R language
language: r
#Define multiple R-versions, one from bioconductor
r:
  - oldrel
  - release
  - devel

script:
- R CMD build . --compact-vignettes=gs+qpdf
- R CMD check --as-cran --use-valgrind bpnreg_2.0.0.tar.gz


addons:
  apt:
    update: true
    packages:
      - libgs-dev
      - qpdf
      - ghostscript
      - valgrind

--tool=memcheck --leak-check=full"

env:
  - VALGRIND_OPTS='--tool=memcheck --leak-check=full --track-origins=yes'

# language: R
# sudo: false
# cache: packages
# warnings_are_errors: false
#
# r_check_args: '--use-valgrind'
#
# addons:
#   apt:
#     packages:
#       - valgrind
# r:
#   - oldrel
#   - release
#   - devel
#

