# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r


# Use R language
language: R

sudo: false
cache: packages
warnings_are_errors: false
r_check_args: '--use-valgrind'

#Define multiple R-versions
r:
  - oldrel
  - release
  - devel

os:
  - linux

addons:
  apt:
    update: true
    packages:
      - qpdf
      - valgrind

env:
  - VALGRIND_OPTS='--tool=memcheck --leak-check=full --track-origins=yes'

