* Encoding: windows-1252.
SORT CASES  BY Condition.
SPLIT FILE SEPARATE BY Condition.

DESCRIPTIVES VARIABLES=PhaseDiff
  /STATISTICS=MEAN STDDEV MIN MAX SEMEAN.

SPLIT FILE OFF.

COMPUTE PhaseDiffStanSD=PhaseDiff / SD.
EXECUTE.

COMPUTE PhaseDiffStanSE=PhaseDiff / SE.
EXECUTE.

ONEWAY PhaseDiffStanSD BY Condition
  /MISSING ANALYSIS
  /POSTHOC=LSD ALPHA(0.05).

ONEWAY PhaseDiffStanSE BY Condition
  /MISSING ANALYSIS
  /POSTHOC=LSD ALPHA(0.05).
